### PR TITLE
Fix shallow git repository issues

### PR DESCRIPTION
**Pull request by jcarpent**
related to #253 or #258.

### CODE REVIEW

**Comment by wxmerkt** [comment]
This may not work on the buildfarm as the source directory is likely to be mounted read-only.

**Comment by jcarpent** [comment]
Are you sure of that?

**Comment by jmirabel** [comment]
It doesn't really change my comment https://github.com/jrl-umi3218/jrl-cmakemodules/pull/258#issuecomment-549303507

I would revert the changes in VERSION_COMPUTE and add another macro that compute the version number from package.xml. I don't really like to automatically guess everything. It is too brittle in this context.

**Comment by jcarpent** [comment]
@jmirabel I do understand your point. I'm first trying to fix what is missing to make git describe more robust, mostly when the git repo is not a deep copy of the original one.

**Comment by wxmerkt** [comment]
The CMake clear way would be to define the version in the CMake, or perhaps the `.version`. Reading it from git describe was kind of the first "brittle" sin which the earlier PR expanded on (if you want to take this viewpoint - the other is, it adds another layer of graceful degradation/robustness before fully failing). I think Justin's fix of "if-git-describe-fails-see-if-package-xml-exists" is a nice graceful way before failing - especially since there is no CMake-error-message/configuration error but a compile (!) error (variable not defined). 

And yes, we should not try to consider the source directory to be writable. It is good practice to consider the source tree to be read-only.

**Comment by jmirabel** [comment]
> The CMake clear way would be to define the version in the CMake

This can still be done project-wise.

**Comment by jcarpent** [comment]
The idea of externalizing the version definition is to allow an easy way to automatize the creation of release with `make release` for instance.
But, we can of course provide a script to perform as well on the CMakeLists with the creation of a commit.

**Comment by wxmerkt** [comment]
Ok, I wasn't aware of the `make release` call. Yet, to come back to this PR, it won't solve the issue encountered - we cannot assume the source tree to be writable. The graceful-failback you've previously added does work (and in my opinion should not be deactivated).

**Comment by jcarpent** [comment]
Following your feedback, I will just raise a warning to detect if the repository is shallow.

**Comment by jcarpent** [comment]
@jmirabel I have just updated the PR.

**Comment by jmirabel** [comment]
I won't block you on this but I still think we have a very complicated way to get the version number. Adding package.xml as an automatic fallback solves one issue and adds confusion.

**Comment by jcarpent** [comment]
I will deal with this concern in an other PR.

**Pull request merged**
