### PR TITLE
Add missing config when creating Python test

### PR DESCRIPTION
**Pull request by jcarpent**

### CODE REVIEW

**Comment by jcarpent** [comment]
This feature is requested on Windows for instance

**Comment by jmirabel** [comment]
Did you check this works find on Linux too ?

**Comment by nim65s** [comment]
According to the [CMake 3.1 doc](https://cmake.org/cmake/help/v3.1/command/add_test.html), 

> The COMMAND and WORKING_DIRECTORY options may use “generator expressions” with the syntax $<...>. See the cmake-generator-expressions(7) manual for available expressions.

So the generator expression for `CONFIGURATION` doesn't seem available.

**Comment by jcarpent** [comment]
This is not the right to operate. I will close this PR then.

**Pull request closed without merging**
