### PR TITLE
Strip and remove duplicates in pkg-config dependencies inside Config.cmake.

### PR DESCRIPTION
**Pull request by jmirabel**

### CODE REVIEW

**Comment by jmirabel** [comment]
This completes #353

**Comment by jcarpent** [comment]
Please wait, discussions are occuring here #350.

**Comment by jcarpent** [comment]
Better to fix #350 than providing pacthes which will be removed then.

**Comment by jcarpent** [comment]
In fact, I did see that you were not changing the same thing

**Comment by jmirabel** [comment]
Thanks for your quick reviews.

**Pull request merged**
