### PR TITLE
[Sphinx] Install doc only if INSTALL_DOCUMENTATION is TRUE

### PR DESCRIPTION
**Pull request by jmirabel**

### CODE REVIEW

**Comment by nim65s** [comment]
This has been in my todolist for more than a year… Thanks for handling it !

**Comment by jcarpent** [comment]
Just to know, the sphinx module does it allow to install documentation of Python bindings?

**Comment by jmirabel** [comment]
> Just to know, the sphinx module does it allow to install documentation of Python bindings?

Yes, it does.

**Comment by jcarpent** [comment]
Thanks a lot for the quick reply. Could you provide an example of use? I will include it to Pinocchio ;)

**Comment by jmirabel** [comment]
Have a look at sot-core/doc/CMakeLists.txt.

**Pull request merged**
