### PR TITLE
boost.cmake: add new PKG_CONFIG_APPEND_BOOST_LIBS macro

### PR DESCRIPTION
**Pull request by bchretien**
This fixes the issue introduced in #76. Now Boost libraries can simply be added with:

```cmake
PKG_CONFIG_APPEND_BOOST_LIBS(filesystem system)
```

If there are specific treatments for OS X, they can be done in this macro.

### CODE REVIEW

**Comment by gergondet** [comment]
Looks good to me. This is cleaner and simpler than current alternatives.

**Comment by bchretien** [comment]
cc @jcarpent

**Comment by jcarpent** [comment]
Looks also great for me. Thanks for this modification.

**Comment by bchretien** [comment]
Tested with roboptim-core on Linux, everything looks fine.

**Comment by jmirabel** [comment]
Shouldn't `PKG_CONFIG_APPEND_BOOST_LIBS(${BOOST_COMPONENTS})` be done automatically in SEARCH_FOR_BOOST macro ?

**Comment by gergondet** [comment]
No. 

Typically, you need the test component if you are using Boost unit test framework but you shouldn't have it in your pkg-config file

**Pull request merged**
