### PR TITLE
[Python] allow compile_pyc from different directories, fix #425

### LINKED ISSUE #425: TARGET 'compile_pyc' was not created in this directory.
Hi,

As noted by @proyan in https://github.com/loco-3d/crocoddyl/pull/809#issuecomment-664992804, #392 introduced a custom target, which break this macro when it is used from multiple CMakeLists.txt.

### PR DESCRIPTION
**Pull request by nim65s**
Hi,

This might not be the best workaround, but I think this does the job.

I'm not sure what was the exact issue on windows that #392 had to fix, though.

### CODE REVIEW

**Comment by jmirabel** [comment]
I think the issue is that the characters allowed for target names are not the same as the one for filenames.

**Comment by nim65s** [comment]
Ok, then this PR ensure that we only have a target name with allowed characters for target names.

**Comment by nim65s** [comment]
I don't see how. `CMAKE_CURRENT_SOURCE_DIR` is the full path.

**Comment by jmirabel** [comment]
> I don't see how. `CMAKE_CURRENT_SOURCE_DIR` is the full path.

Two paths which differs only from a character that matches your regex will generate the same target. But, you are right, in this case, there is no parent/child relation between the two.

**Pull request merged**
