### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by jmirabel**
Provides templates for automatically generated documentation and hosting on readthedocs. See http://jrl-cmakemodules.readthedocs.io

Related to #66

### CODE REVIEW

**Comment by jmirabel** [comment]
When this is merged, @gergondet could you change the "Repository URL" on this page to point to https://readthedocs.org/dashboard/jrl-cmakemodules/edit/. I do not have the rights to add a webhook on this repo.

**Comment by jmirabel** [comment]
Is this ready to be merged ?

I updated the doc for the parts on which I contributed.

**Comment by gergondet** [comment]
I've made some changes but otherwise that's a great job.

I'm merging and changing the

**Comment by jmirabel** [comment]
Thanks ! I forgot to update the README.md which could include a link to the documentation.

**Comment by gergondet** [comment]
I didn't think about it either. Fixed in ad1077d

**Pull request merged**
