### PR TITLE
Remove license header

### PR DESCRIPTION
**Pull request by jcarpent**

### CODE REVIEW

**Comment by jmirabel** [comment]
Any reason for this ?

**Comment by jcarpent** [comment]
There is no real reason to propagate this license towards the packages that use jrl-cmake-modules

**Comment by jmirabel** [comment]
First of all, the license is not *propagated*. It is restricted to the 3 files that are generated and does not influence in any way the license of the software.

The license here makes it explicit to people that they can do whatever they want with this file.

**Comment by jcarpent** [comment]
I do think there is a reason to put a license on a generated files, but I would rather suggest to directly refer to the one from the sofware which uses jrl-cmake. 
I think this adding noise where there is no need.

**Comment by jmirabel** [comment]
The message is not very explicit to that extend. You should likely add a statement like
```
///////////////////////////////////////////////////////////////////////////////
// BSD 2-Clause License
// Copyright (C)  2008-2018 LAAS-CNRS, JRL AIST-CNRS, INRIA. 
// See <some link>
///////////////////////////////////////////////////////////////////////////////
```

By the way, this project is LGPL so removing the license of these headers makes them LGPL, which is the opposite to https://github.com/jrl-umi3218/jrl-cmakemodules/pull/126

**Comment by jcarpent** [comment]
We then just need this file follows the rules of the targeted project, would be simpler and less borring.

**Comment by jmirabel** [comment]
a. You are not the author of the file so you cannot decide by yourself to change its license.
b. Can the file be orphaned and its authorship and license be modified at configure time ? That sounds weird to me.

**Comment by jcarpent** [comment]
a. Indeed, you are correct with this respect.
BUT, I do think the intention of this file is to propagate a license which has nothing to do with the end-user project. 
I've removed this line, because when I was working on the version, I was really surprised to see these headers which were not instructive, and was leading to some confusion.
I think it is better to make these files generic enough, and to avoid putting license on it. I was much more in favor of linking them to the generated files, which seems the correct way of knowing their origin for further modifications.

But again, if you want to revert this PR, feel free to do it. But, I do not see any converging point.

**Comment by jcarpent** [comment]
Or add the header you suggested, I would not stop you.

**Pull request merged**
