### PR TITLE
Fixes #206

### LINKED ISSUE #206: boost_python library could not be found on Ubuntu 19.04
I get the following error from CMake trying to find boost python libraries:

```
CMake Warning at /usr/share/cmake-3.13/Modules/FindBoost.cmake:1775 (message):
  No header defined for python-py37; skipping header check
Call Stack (most recent call first):
  cmake/boost.cmake:104 (FIND_PACKAGE)
  CMakeLists.txt:169 (SEARCH_FOR_BOOST)


CMake Error at /usr/share/cmake-3.13/Modules/FindBoost.cmake:2100 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.67.0

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_python-py37

  Some (but not all) of the required Boost libraries were found.  You may
  need to install these additional Boost libraries.  Alternatively, set
  BOOST_LIBRARYDIR to the directory containing Boost libraries or BOOST_ROOT
  to the location of Boost.
Call Stack (most recent call first):
  cmake/boost.cmake:104 (FIND_PACKAGE)
  CMakeLists.txt:169 (SEARCH_FOR_BOOST)


CMake Error at cmake/boost.cmake:107 (MESSAGE):
  Failed to detect Boost with the following components:

Call Stack (most recent call first):
  CMakeLists.txt:169 (SEARCH_FOR_BOOST)
```

The library name on my system is `boost_python37`, not `boost_python-py37`. 

Changing the lines
```cmake
IF(APPLE OR NETBSD_FOUND OR ARCHLINUX_FOUND)
          SET(BOOST_PYTHON_COMPONENT "python${PYTHON_VERSION_MAJOR}${PYTHON_VERSION_MINOR}")
        ELSEIF(DEBIAN_FOUND)
          SET(BOOST_PYTHON_COMPONENT "python-py${PYTHON_VERSION_MAJOR}${PYTHON_VERSION_MINOR}")
        ELSE(APPLE OR NETBSD_FOUND OR ARCHLINUX_FOUND)
          SET(BOOST_PYTHON_COMPONENT "python${PYTHON_VERSION_MAJOR}")
        ENDIF(APPLE OR NETBSD_FOUND OR ARCHLINUX_FOUND)
```
to
```cmake
IF(APPLE OR NETBSD_FOUND OR ARCHLINUX_FOUND OR DEBIAN_FOUND)
          SET(BOOST_PYTHON_COMPONENT "python${PYTHON_VERSION_MAJOR}${PYTHON_VERSION_MINOR}")
        ELSE(APPLE OR NETBSD_FOUND OR ARCHLINUX_FOUND)
          SET(BOOST_PYTHON_COMPONENT "python${PYTHON_VERSION_MAJOR}")
        ENDIF(APPLE OR NETBSD_FOUND OR ARCHLINUX_FOUND OR DEBIAN_FOUND)
```
in https://github.com/jrl-umi3218/jrl-cmakemodules/blob/master/boost.cmake#L73 fixes the problem for me.

### PR DESCRIPTION
**Pull request by mkatliar**

### CODE REVIEW

**Comment by nim65s** [comment]
Thanks for the heads up. I'll check this on a few distributions tomorrow.

**Comment by nim65s** [comment]
> This looks good to me. Maybe @nim65s could review it too ?

@jmirabel : It looks like you are in the future… This is not 22:51 UTC+2 yet, please come back :)

**Comment by nim65s** [comment]
```
┬─[gsaurel@akasan:~]─[13:52:43]
╰─>$ for v in 14.04 16.04 18.04 19.04
         echo $v
         docker run --rm -t ubuntu:$v sh -c 'apt-get update -qqy && apt-get install -qqy libboost-python-dev > /dev/null 2> /dev/null && dpkg -L $(apt-cache depends libboost-python-dev | tail -n1 | cut -d: -f2) | grep ".so\$"'
     end
14.04
/usr/lib/x86_64-linux-gnu/libboost_python-py27.so
/usr/lib/x86_64-linux-gnu/libboost_python-py34.so
/usr/lib/x86_64-linux-gnu/libboost_python.so
16.04
/usr/lib/x86_64-linux-gnu/libboost_python-py27.so
/usr/lib/x86_64-linux-gnu/libboost_python-py35.so
/usr/lib/x86_64-linux-gnu/libboost_python.so
18.04
/usr/lib/x86_64-linux-gnu/libboost_python-py27.so
/usr/lib/x86_64-linux-gnu/libboost_python-py36.so
/usr/lib/x86_64-linux-gnu/libboost_python.so
/usr/lib/x86_64-linux-gnu/libboost_python3-py36.so
/usr/lib/x86_64-linux-gnu/libboost_python3.so
19.04
/usr/lib/x86_64-linux-gnu/libboost_python.so
/usr/lib/x86_64-linux-gnu/libboost_python27.so
/usr/lib/x86_64-linux-gnu/libboost_python3-py37.so
/usr/lib/x86_64-linux-gnu/libboost_python3.so
/usr/lib/x86_64-linux-gnu/libboost_python37.so
```

This is pure madness. Or Evil. Or Both, I don't know.

**Comment by jmirabel** [comment]
Has anyone asked how to look for Boost Python with CMake, on a forum or to a boost mailing list ?

**Comment by nim65s** [comment]
I cant' find anythin in Boost doc. [CMake doc](https://cmake.org/cmake/help/latest/module/FindBoost.html) says:
> Note that Boost Python components require a Python version suffix (Boost 1.67 and later), e.g. python36 or python27 for the versions built against Python 3.6 and 2.7, respectively. This also applies to additional components using Python including mpi_python and numpy. Earlier Boost releases may use distribution-specific suffixes such as 2, 3 or 2.7. These may also be used as suffixes, but note that they are not portable.

For me, the issue is that Debian chose to install stuff in a non standard way (until Stretch), and now they decided to follow the standard, starting from Buster, without providing links to support their old way.  And Ubuntu followed.

So I suggest to try to look for `pythonXY`, then `python-pyXY`, then `pythonX` and stop trying to find on which distribution we are.

**Comment by nim65s** [comment]
In any case, this PR must not be merged, as this code will not work in Ubuntu <= 18.04

**Comment by jcarpent** [comment]
OK. Sounds a good strategy to try the various signatures in the historical order.

**Comment by jcarpent** [comment]
@nim65s Could implement the strategy you suggested?

**Comment by nim65s** [comment]
I am not available until May 28th. But if you can wait until then, I can implement that.

**Comment by jcarpent** [comment]
I will take it in charge, as from my side, we have encountered the same troubles.

**Comment by jcarpent** [comment]
Solved by #213

**Pull request closed without merging**
