### PR TITLE
Fix warning

### PR DESCRIPTION
**Pull request by jcarpent**
To avoid the warning as refered in http://build.ros.org/job/Kdev__eigenpy__ubuntu_xenial_amd64/46/cmake/new/folder.94772433/category.2333/

### CODE REVIEW

**Comment by jcarpent** [comment]
@jmirabel Can you check this PR?

**Comment by jmirabel** [comment]
I believe the correct fix is ed1152c

**Comment by jcarpent** [comment]
OK. Could you push on top of this?

**Comment by jmirabel** [comment]
I don't think it is a good idea to introduced old policies so it would be better to remove your commit. Don't you think ?

**Comment by jcarpent** [comment]
Yep, I do agree. I close this PR and you open a new one?

**Pull request closed without merging**
