### PR TITLE
[config.hh] Add @LIBRARY_NAME@_VERSION_AT_LEAST

### PR DESCRIPTION
**Pull request by gabrielebndn**
This would save lots of boilerplate, and it would provide all of our packages with a uniform interface.

### CODE REVIEW

**Comment by gabrielebndn** [comment]
@nim65s, what do you think?

**Comment by nim65s** [comment]
@jmirabel this could be useful to handle deprecation in an even smoother way, so why not

**Comment by gabrielebndn** [comment]
I do not see much need of it, but why not, I pushed `@LIBRARY_NAME@_VERSION_AT_MOST` too. If you do not spot any error, I think you can merge this PR

**Comment by jmirabel** [comment]
Looks good to me.

**Pull request merged**
