### PR TITLE
os: split in a separate file the definition of OS checker

### PR DESCRIPTION
**Pull request by jcarpent**
I need to define first the CHECK_{DEBIAN,NETBSD,etc} first before including `INCLUDE(${CMAKE_CURRENT_LIST_DIR}/GNUInstallDirs.cmake)`

### CODE REVIEW

**Comment by nim65s** [comment]
cc @olivier-stasse

**Comment by jcarpent** [comment]
@nim65s @nim65s Did you encounter the same issue?

**Comment by nim65s** [comment]
I was able to make a release without issue, but at the same time @olivier-stasse got an issue… So I wanted to investigate on the differences, but if you just fix it that's fine for me :)

**Comment by jcarpent** [comment]
It seems working on my side. I will merge it to move forward.

**Pull request merged**
