### PR TITLE
Add a module to find QPOases solver. USE : SEARCH_FOR_QPOASES()

### PR DESCRIPTION
**Pull request by MaximilienNaveau**
Add a cmake module to link against QPOases a solver for quadratic optimisation problem.

### CODE REVIEW

**Comment by jmirabel** [comment]
:+1:

**Comment by MaximilienNaveau** [comment]
In fact the .cmake is not good enough to be merged so I will close this pull request.

**Comment by bchretien** [comment]
Another possibility would be to send a patch to qpOASES developers adding pkg-config support. They already use CMake so this is fairly straightforward, but then users would need to use the latest version. AFAIK it's not packaged in many distributions yet (I'm maintaining the one for Arch, but for Ubuntu it's [in their todo list](https://projects.coin-or.org/qpOASES/ticket/25)), so this should not be much of a problem either.

**Comment by MaximilienNaveau** [comment]
In fact, we used a "private cmake" folder containing the findqpoases.cmake file to not pollute the jrlcmakemodule with a not well written cmake file.

**Comment by jmirabel** [comment]
For those who are interested, I have packaged qpOASES using this repository: https://github.com/jmirabel/qpOASES

**Pull request closed without merging**
