### PR TITLE
Boost: don't export python, fix #422, fix #423

### LINKED ISSUE #422: Boost::Python export on 16.04
Hi,

Following #407, I have several errors about the fact that we export a Boost::Python dependency under a made up name.

Here is the first.

On 16.04 (CMake 3.5), I can build and install eigenpy fine with Python 3. But then, when I want to configure hpp-fcl:
```
-- eigenpy searched on  FOUND. eigenpy at /tmp/3/lib/libeigenpy.so
-- boost_python-py35 searched on  FOUND. boost_python-py35 at /usr/lib/x86_64-linux-gnu/libboost_python-py35.so
CMake Error at /usr/share/cmake-3.5/Modules/FindBoost.cmake:1677 (message):
  Unable to find the requested Boost libraries.

  Boost version: 1.58.0

  Boost include path: /usr/include

  Could not find the following Boost libraries:

          boost_python35

  No Boost libraries were found.  You may need to set BOOST_LIBRARYDIR to the
  directory containing Boost libraries or BOOST_ROOT to the location of
  Boost.
Call Stack (most recent call first):
  /tmp/3/lib/cmake/eigenpy/eigenpyConfig.cmake:123 (find_package)
  CMakeLists.txt:75 (FIND_PACKAGE)
```

Where `CMakeLists.txt:75` is `FIND_PACKAGE(eigenpy 2.2 REQUIRED)`, and `/tmp/3/lib/cmake/eigenpy/eigenpyConfig.cmake:123` is `find_package(Boost COMPONENTS python35 REQUIRED)`.

This issue is [breaking build on robotpkg](http://robotpkg.openrobots.org/rbulk/robotpkg/path/py-hpp-fcl/py35-hpp-fcl-1.4.5/Ubuntu-16.04.pal-x86_64/bulk.html)

Adding the generated `find_package(Boost COMPONENTS python35 REQUIRED)` in various places, I found that the issue is raised if this line is added before that one

https://github.com/jrl-umi3218/jrl-cmakemodules/blob/fb4c22c319ec5320f9a85527eb1a4130954846f5/boost.cmake#L61

So, should we ship this `FindBoost.cmake` ? Or do we have another solution ?
Removing Boost::Python from the exports would be a workaround too.

In any case, I think that we should ensure that the ways we find Boost and its components are the same, whether we are in the main CMakeLists.txt or in a generated xxxConfig.cmake.

### LINKED ISSUE #423: Boost::Python export on Arch
Hi,

Following #407, I have several errors about the fact that we export a Boost::Python dependency under a made up name.

Here is the second, following #422

On ArchLinux (CMake 3.18), I get:
```
-- eigenpy searched on  FOUND. eigenpy at /tmp/3/lib/libeigenpy.so
-- boost_python3 searched on  FOUND. boost_python3 at /usr/lib/libboost_python3.so
CMake Error at /usr/lib64/cmake/Boost-1.72.0/BoostConfig.cmake:120 (find_package):
  Could not find a package configuration file provided by "boost_python3"
  (requested version 1.72.0) with any of the following names:

    boost_python3Config.cmake
    boost_python3-config.cmake

  Add the installation prefix of "boost_python3" to CMAKE_PREFIX_PATH or set
  "boost_python3_DIR" to a directory containing one of the above files.  If
  "boost_python3" provides a separate development package or SDK, be sure it
  has been installed.
Call Stack (most recent call first):
  /usr/lib64/cmake/Boost-1.72.0/BoostConfig.cmake:185 (boost_find_component)
  /usr/share/cmake-3.18/Modules/FindBoost.cmake:448 (find_package)
  /usr/share/cmake-3.18/Modules/CMakeFindDependencyMacro.cmake:47 (find_package)
  /tmp/3/lib/cmake/eigenpy/eigenpyConfig.cmake:128 (find_dependency)
  CMakeLists.txt:75 (FIND_PACKAGE)
```

I'll open a PR for this.

### PR DESCRIPTION
**Pull request by nim65s**
Hi,

I checked this workaround on 16.04 & arch :  bulding eigenpy then hpp-fcl worked fine.

### CODE REVIEW

**Comment by jcarpent** [comment]
I think we should only export for some Boost components when doing so. No all of them have to be exported.

**Comment by jmirabel** [comment]
I think we shouldn't use this macro for anything else than Boost Python.

For other component, use
- `ADD_PROJECT_DEPENDENCY(Boost COMPONENTS components REQUIRED)` if you want some components to be exported and
- `find_package(Boost COMPONENTS components REQUIRED)` otherwise.

**Comment by jmirabel** [comment]
Maybe this macro should become deprecated in favor of `SEARCH_FOR_BOOST_PYTHON`.

**Comment by jcarpent** [comment]
I do agree that we should introduce `SEARCH_FOR_BOOST_PYTHON` and everything will be fine.
But we also need to export Boost.Python, for instance in Pinocchio, the Python parser relies on it.

**Comment by jmirabel** [comment]
>  But we also need to export Boost.Python, for instance in Pinocchio, the Python parser relies on it.

In general, you do not need to export it. This is a specific case. I suggest either to do it in Pinocchio or, if done in the repo, to do it only when explicitly asked.

**Comment by nim65s** [comment]
the main eigenpy lib also needs it: https://github.com/stack-of-tasks/eigenpy/blob/master/src/eigenpy.cpp#L35

**Comment by nim65s** [comment]
So we agreed on 
1. introducing `SEARCH_FOR_BOOST_PYTHON`
2. deprecating `SEARCH_FOR_BOOST`

Right ?
I can handle this if necessary. But shouldn't we merge this PR until then ?

**Comment by jcarpent** [comment]
We do agree. Please go ahead on top of this PR I would say.

**Comment by nim65s** [comment]
This doesn't work on python 2 / 18.04. I'm trying to avoid committing space changes, which made me miss an indentation issue, which broke my view of the logic, and the logic is wrong here. I'll directly work on `SEARCH_FOR_BOOST_PYTHON` then.

**Pull request closed without merging**
