### PR TITLE
Make Boost components exportable.

### PR DESCRIPTION
**Pull request by jmirabel**

### CODE REVIEW

**Comment by jmirabel** [comment]
I tried it in hpp-fcl and it worked fine. Could we get this merge ?

**Comment by nim65s** [comment]
Do we have a way to specify components that don't need to be exported, eg. unit tests ?

**Comment by jmirabel** [comment]
For those ones, you can use `find_packge` directly.

**Comment by jmirabel** [comment]
Actually, the only reason to keep `SEARCH_FOR_BOOST` is Boost Python. We could remove altogether SEARCH_FOR_BOOST and keep only a single SEARCH_FOR_BOOST_PYTHON macro.

**Pull request merged**
