### PR TITLE
[sdformat] check for different sdformat packages, and add project dependency when found

### PR DESCRIPTION
**Pull request by proyan**

### CODE REVIEW

**Review by jcarpent — CHANGES_REQUESTED** [review]
Could you automatize the process, meaning it would be easy to handle just a list of versions?
In addition, I would suggest relying on the latest version first.

**Comment by proyan** [comment]
The last commit should handle both your suggestions.

**Review by jcarpent — APPROVED** [review]
Much more elegant ;) Thanks a lot.

**Comment by nim65s** [comment]
Maybe we could add a `REQUIRED` argument, that raise an error on reaching the end of the loop ?

**Comment by proyan** [comment]
@nim65s That is a good suggestion. https://github.com/jrl-umi3218/jrl-cmakemodules/pull/501/commits/d9df3999735feb0402d88c142fd517a7ecb7d99f should take care of that

**Review by nim65s — APPROVED** [review]
thanks !

**Pull request merged**
